### ISSUE TITLE
Changing the default root shell to /bin/sh?

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/cheribsd#1060]
Most of our users will not be familiar with csh since other operating systems generally default to bash/zsh/some other POSIX sh compatible shell. Switching the root shell to `/bin/sh`. Personally I also find csh extremely awkward to work with. Now that /bin/sh can actually complete commands from $PATH I see no reason to use csh. 

A more recent annoyance is that I spent ages today trying to figure out why double clicking on files in dolphin would fail to open the appropriate program.
I was running dolphin under GDB, and `show environment` tells me that PATH contains the directory where I am expecting the target program.
However, because gdb uses the default $SHELL to start programs PATH will be reset to _PATH_DEFPATH (see also https://github.com/CTSRD-CHERI/gdb/issues/46).

Resetting the user-provided environment when running non-interactively is really confusing.

**Comment by bsdjhb** [comment]
This was done upstream and merged into CheriBSD in 26f913b9a5aefe876328b8c349c69741edd7c35b.
