### ISSUE TITLE
Rename CHERI_PERM_CHERIABI_VMMAP

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/cheribsd#1062]
This permission applies to both the mmap family of APIs and shmdt so VMMAP is not the right name.  Additionally, the permission isn't strictly tied to CheriABI (in a hybrid world were not all of VA is part of DDC, we would want to use this permission for the APIs that manage VA outside DDC.)

The proposed replacement is CHERI_PERM_VMMAN.

**Comment by bsdjhb** [comment]
Superhero connotations are ok with me.  If you wanted something shorter you could perhaps just use `CHERI_PERM_VM`.  One observation is that VM is now an overloaded term in systems software (virtual memory vs virtual machines) so `CHERI_PERM_VMEM` might be less ambiguous.

**Comment by kevin-brodsky-arm** [comment]
VMMAN is supposed to be a shorthand for Virtual Memory Management, but I do see the superhero connotation now! VMEM would be fine as well I suppose.

One aspect that I find potentially confusing with `CHERI_PERM_VMMAN` or similar is that it doesn't distinguish that software-defined permission from the hardware-defined permissions. Maybe `CHERI_PERM_SW_VMMAN` would work?

**Comment by brooksdavis** [comment]
Further discussion has us leaning toward `CHERI_PERM_VMEM` or `CHERI_PERM_SW_VMEM` with the non-code spelling being "VMem"

**Comment by brooksdavis** [comment]
After further discussion we'll go with `CHERI_PERM_SW_VMEM`
