### ISSUE TITLE
Cannot expand root filesystem

### ISSUE THREAD

**Issue by NatSavBS** [CTSRD-CHERI/cheribsd#1069]
Hi,

I am experimenting with cheri to potentially migrate one of our IOT projects to a more secure platform however I am running into some issues with expanding the root filesystem of the virtual machine. I have successfully made the drive bigger with qemu-img however I am having trouble getting the partitions to expand.

Gpart resize returns "inappropriate ioctl for device". I also tried resizing the partitions with fdisk on the host OS however that caused the system to fail to mount the root (although the partition would mount if manually selected)

Any tips or advice would be much appreciated!

**Comment by jrtc27** [comment]
Fixed in #1143
