### ISSUE TITLE
CHERIABI stack too small for tests

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#109]
See: CTSRD-CHERI/cheri-c-tests#2

The CHERIABI stack is 256KB, some tests expect 1-2MB.  The FreeBSD default is `1MB*sizeof(void*)`, which would be 32MB on CHERI - this is probably slightly excessive, but 8MB would be a lot more realistic.

**Comment by brooksdavis** [comment]
I clearly misread the code that sets the maximum stack size.  Where is the `1MB*sizeof(void*)` limit defined?

**Comment by brooksdavis** [comment]
Increased to 8MB in 580cfb8b39a685ad586e0f870213031042842554.  Fixes CTSRD-CHERI/cheri-c-tests#2.
