### ISSUE TITLE
Change trusted-stack APIs and ABIs to support configurable / variable-length stacks

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#11]
Currently, the sysarch() system calls used by userspace to inspect and modify kernel-maintained trusted stacks embed a notion of a fixed-size trusted stack. Once trusted stacks are allowed to grow (see #10), we will want userspace to be able to behave more flexibly -- and to be able to change the trusted stack size at runtime if needed.

Linked to #10  -- arguably, dependent on it.

**Comment by jrtc27** [comment]
libcheri was removed in #1056
