### ISSUE TITLE
CheriBSD/Morello bhyve support to host CHERI-enabled guests

### ISSUE THREAD

**Issue by gvnn3** [CTSRD-CHERI/cheribsd#1104]
Good bhyve support for hosting ordinary aarch64 with FreeBSD
Good bhyve support for hosting Morello-enabled virtual-machine instances able to run CheriABI, etc.

**Comment by kwitaszczyk** [comment]
Fixed by https://github.com/CTSRD-CHERI/cheribsd/issues/1173.
