### ISSUE TITLE
Support multiple MK_LIB* compats during build

### ISSUE THREAD

**Issue by gvnn3** [CTSRD-CHERI/cheribsd#1115]
In theory upstream could benefit from it on AArch64 so it could build lib32+libsoft for AArch32 binaries, but currently AArch64 doesn’t even build lib32 userspace, only the freebsd32 kernel parts
CheriBSD wip-multicompat branch has an unpolished-but-working implementation
Has some hacks in bsd.compat.mk to work around Clang/LLVM silliness on MIPS
Inconsistent naming of variables could be improved

**Comment by jrtc27** [comment]
https://github.com/CTSRD-CHERI/cheribsd/pull/1727
