### ISSUE TITLE
test_nofault_ccall_dli_creturn failure

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#114]
With the latest compiler changes, `test_nofault_ccall_dli_creturn` is failing.  This appears to be because the construction of the sandbox capabilities is too restrictive now that addresses of globals are bounds checked.

**Comment by rwatson** [comment]
Fixed in a44eae, but other supporting commits to add ```.size``` for additional test functions, and to avoid use of ```cheri_codeptrperm()``` in pure-capability compilation, were also required. These tests now appear to pass for both ```cheritest``` and ```cheriabitest```.
