### ISSUE TITLE
re(4) needs adding to GENERIC(-MORELLO) and/or PNP info

### ISSUE THREAD

**Issue by jrtc27** [CTSRD-CHERI/cheribsd#1150]
Neither are present so out of the box on a Morello board (or N1SDP) you have no NIC and need to kldload it.

**Comment by jrtc27** [comment]
(NIC is a RealTek RTL8111GS, which FreeBSD calls "RealTek 8168/8111 B/C/CP/D/DP/E/F/G PCIe Gigabit Ethernet")

**Comment by bsdjhb** [comment]
I would just add 'device re' in arm64 GENERIC upstream and we can loop it back in (or cherry-pick it for the release if we haven't caught up by then)

**Comment by jrtc27** [comment]
Yeah, you'll want it for netbooting anyway (well, there's re_load=YES in loader.conf, but that's still not an it-just-works-out-of-the-box experience).

**Comment by jrtc27** [comment]
Added upstream in https://github.com/CTSRD-CHERI/cheribsd/commit/509a006205230e7092ec70d2def6665f592dc69a
