### ISSUE TITLE
libcheri.3 could provide a more tutorial-like introduction to compartmentalisation

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#120]
The libcheri(3) man page does document a recent version of the libcheri APIs.

**Comment by rwatson** [comment]
Will investigate and update (perhaps with help from @brooksdavis).

**Comment by rwatson** [comment]
A few updates in 8b94bd2f1ce11ab772751792cd0558d1180d39a8, b495cc4d6351ef11de6a32c982b4c3b5bd812df2, and ae28678c8c53a0cfc18e0aa378a17c9dbb13449c. More substantive changes around compiler support to follow.

**Comment by jrtc27** [comment]
libcheri was removed in #1056
