### ISSUE TITLE
Switch to new Morello varargs ABI

### ISSUE THREAD

**Issue by jrtc27** [CTSRD-CHERI/cheribsd#1249]
Will need:
* Passing `-Xclang -morello-vararg=new` (until it becomes the default)
* Updating syscall(2) implementation

Toolchain support merged to morello/dev on 10th December, so likely not able to assume its existence quite yet in users' existing builds.

NB: Also a breaking change for hybrid, where it changes how capabilities are passed to variadic functions (from registers to indirectly), though relatively limited

**Comment by bsdjhb** [comment]
We probably want to do this before the first release so we don't have to deal with a flag day for this later?

**Comment by jrtc27** [comment]
Yeah... fun for native builds I imagine

**Comment by bsdjhb** [comment]
Looks like the syscall() handling in the kernel already assumes all the arguments are only in registers?

**Comment by jrtc27** [comment]
Oh right, yeah, because the whole point is it _does_ use registers and that doesn't catch overflow, the new ABI is what shoves everything on the stack and creates a bounded capability

**Comment by kwitaszczyk** [comment]
The new var-args ABI was merged to `dev` and released in 22.05. CheriABI packages and hybrid ABI packages were rebuilt with the new ABI and verified.
