### ISSUE TITLE
libcheri needs a 'malloc from outside' interface

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#134]
Several more-privileged APIs need to return a pointer to the compartment.  Ideally, this would typically be allocated within the compartment's address range so that it can be automatically freed when the compartment is destroyed.  There are a few variations:
- Code in the compartment should be able to call `free` on the result (i.e. the equivalent of ccalling `malloc` from outside).
- Code in the compartment should not be able to deallocate or re-map the allocated memory (i.e. provide some pages that can be completely controlled from a more privileged context outside).

**Comment by jrtc27** [comment]
libcheri was removed in #1056
