### ISSUE TITLE
rc.d and motd warnings if WITNESS, INVARIANTS, malloc debugging, etc., are enabled

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#1342]
With a relatively new community of CheriBSD users forming, who are generally expected to be inexperienced with FreeBSD, we need to make it extremely clear when performance-harmful debug options are enabled by default in the kernel and userspace. Two possibilities, likely both of which should be pursued, are:

- An rc.d script running at the very end of the boot that checks various relevant sysctls and libc options
- An rc.d script that updates /etc/motd to include debugging feature warnings at login when they are enabled

**Comment by brooksdavis** [comment]
Resolved in #1375 and followups.
