### ISSUE TITLE
Unexpected mmap failure with MAP_ALIGNED and attempt to shadow

### ISSUE THREAD

**Issue by rmn30** [CTSRD-CHERI/cheribsd#1365]
I am seeing an unexpected failure of mmap with the following test run on cheri-riscv64-purecap:
```
#include <stdio.h>
#include <sys/mman.h>
#include <assert.h>

int main (int argc, char **argv)
{
  void* p1 = mmap(0, 0x200000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON | MAP_ALIGNED(21), -1, 0);
  assert(p1 != MAP_FAILED);
  void* p2;
  p2 = mmap(p1, 0x20000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FIXED | MAP_ANON, -1, 0);
  assert(p2 == p1);
  p2 = mmap(p1, 0x40000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FIXED | MAP_ANON, -1, 0);
  assert(p2 == p1);
  return 0;
}
```
The third mmap fails with ` errno 12 Cannot allocate memory`. Removing the `MAP_ALIGNED` from the first `mmap` or commenting out the second causes the third one to succeed.

For context, this was reduced from a `ktrace` of an `snmalloc` test. `snmalloc` uses `mmap` with `MAP_FIXED | MAP_ANON` to zero larger regions of memory after an initial reservation.

**Comment by rmn30** [comment]
@bsdjhb , @nwf any thoughts on this?

**Comment by brooksdavis** [comment]
I got started looking into this on Friday but had a lot of tooling problems. Thus far it looks like there's a failure to consolidate `MAP_ENTRY_UNMAPPED` entries after `vm_map_delete()` in `vm_map_fixed()`. This leads to two unmapped entries in a row from the same reservation, the first of which is 0x20000 long causing this to fail in `vm_map_insert()`:
```
                if ((new_entry->eflags & MAP_ENTRY_UNMAPPED) == 0 ||
                    new_entry->end < end)
                        return (KERN_NO_SPACE);
```
The problem seem to be that `vm_map_delete()` only attempts to consolidate downward and it needs to consolidate upward as well. I'm trying a build with the patch now.

**Comment by brooksdavis** [comment]
My first patch didn't work, but this assertion detects the flaw I think is there:
```C
diff --git a/sys/vm/vm_map.c b/sys/vm/vm_map.c
index cdef2f8b0572..ea9fa01ff073 100644
--- a/sys/vm/vm_map.c
+++ b/sys/vm/vm_map.c
@@ -4439,6 +4439,13 @@ vm_map_delete(vm_map_t map, vm_offset_t start, vm_offset_t end,
                        }
                        /* Attempt to consolidate the mapping anyway? */
                        vm_map_try_merge_entries(map, scratch_entry, entry);
+                       /*
+                        * We should now have a single MAP_ENTRY_UNMAPPED
+                        * entry that at least spans whole delete
+                        * region.
+                        */
+                       KASSERT(entry->start <= start, ("entry->start (%ju) > start (%ju)", entry->start, start));
+                       KASSERT(entry->end >= end, ("entry->end (%ju) < end (%ju)", entry->end, end));
                } else {
                        vm_map_entry_delete(map, entry);
                }
```
The intuition is that now we've punched a hole in the existing reservation and there should be a single `MAP_ENTRY_UNMAPPED` entry spanning that space. Otherwise something has gone wrong.

**Comment by qwattash** [comment]
Perhaps we should check for the assumed invariant that there are never two contiguous `VM_MAP_UNMAPPED` entries in `_vm_map_assert_consistent`? I'm currently trying to keep track of these design notes in a google doc. I have been meaning to add a section on coalescing policies.

**Comment by brooksdavis** [comment]
Fixed in dev, will be merged to main soon.
