### ISSUE TITLE
libmalloc_simple reads uninitialized memory

### ISSUE THREAD

**Issue by hbcam** [CTSRD-CHERI/cheribsd#138]
See #136.
Had to do that in CheriOS, else op->ov_next can be a non-NULL not valid pointer.
It is checked against NULL and since it is not NULL, is dereferenced, triggering a tag violation.

If #136 makes sense, #137 might be useful to pull too.

**Comment by brooksdavis** [comment]
libmalloc_simple is designed for the process model which assumes that uninitialized memory is zero.  The best solution is to modify the CheriOS version of `__morepages()` to zero the pages it returns to `morecore()`.

**Comment by hbcam** [comment]
I'll do that.
