### ISSUE TITLE
Implement support for CHERI branch instructions in MipsEmulateBranch()

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#140]
`MipsEmulateBranch()` is used in various trap-handling cases, such as userspace and kernel breakpoints, to emulation branch instructions when exceptions are taken in branch-delay slots. Currently, `MipsEmulateBranch()` emulates a range of MIPS branch instructions, but not CHERI branch instructions. This issue is intended to track implementing the missing CHERI branch instructions, which include `CBTU`, `CBTS`, `CJR`, and `CJALR`.

**Comment by bsdjhb** [comment]
OBE
