### ISSUE TITLE
Buffer overrun with binary data in less(1)

### ISSUE THREAD

**Issue by tmarkettos** [CTSRD-CHERI/cheribsd#1426]
I found a buffer overrun when using less(1) with a binary file.  There is a high chance that any binary file >256 bytes will trigger a capability exception.

PR to upstream here:
https://github.com/gwsw/less/pull/271/commits

Not sure if we want to consume that directly or wait for upstream to come in via FreeBSD.

**Comment by brooksdavis** [comment]
Fixed with #1431
