### ISSUE TITLE
Reentrant and threading-safe system objects using libcheri

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#147]
Currently, there is a single global stack used on entering CHERI system objects (`CHERI_ENTER_STACK_SIZE` size for `__cheri_enter_stack`). To properly handle reentrance of the system object, and multithreading, a better solution is required.

**Comment by davidchisnall** [comment]
We're not currently using this for any of the eval, but it's a bit of an omission (other sandboxing things can do it quite happily).  Currently, the JVM manages clearing stacks and it would be good to move that responsibility into libcheri, so it manages a pool of stacks and clears them on return (ideally in a background thread).

**Comment by jrtc27** [comment]
libcheri was removed in #1056
