### ISSUE TITLE
pmcstat is currently broken

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/cheribsd#1509]
On current dev we get a SIGPROT immediately - this can be fixed by cherry-picking https://github.com/freebsd/freebsd-src/commit/1f5679569dd42a9e431f0a40c820bc0d40f51ba5, but then we get `ERROR: Initialization of the pmc(3) library failed`. According to @jrtc27 this happens because the newly added cmn and dmc events overlap our event space.

**Comment by jrtc27** [comment]
Fixed by #1512
