### ISSUE TITLE
drm_gem mutex warning

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#1553]
With WITNESS and INVARIANTS enabled, and running with a pure-capability kernel from the 11 November 2022 CheriBSD development snapshot, I intermittently see the following warning:

```WARNING !mutex_is_locked(&obj->dev->struct_mutex) failed at /local/scratch/jenkins/workspace/CheriBSD-pipeline_dev@3/cheribsd/sys/dev/drm/core/drm_gem.c:1048```

I’m not certain what is triggering this warnings. Wayland is running on the video console, but I’m not in my office so it’s not a specific thing driven by user activity.

```
FreeBSD cheri-blossom.sec.cl.cam.ac.uk 14.0-CURRENT FreeBSD 14.0-CURRENT #0 8bbb70a41b0: Fri Nov 11 11:22:40 UTC 2022     jenkins@ctsrd-build-linux-15:/local/scratch/jenkins/workspace/CheriBSD-pipeline_dev@3/cheribsd-morello-purecap-build/local/scratch/jenkins/workspace/CheriBSD-pipeline_dev@3/cheribsd/arm64.aarch64c/sys/GENERIC-MORELLO-PURECAP arm64
```

**Comment by rwatson** [comment]
Tagging @gvnn3.

**Comment by bukinr** [comment]
https://github.com/CTSRD-CHERI/cheribsd/pull/1579

**Comment by brooksdavis** [comment]
https://github.com/CTSRD-CHERI/cheribsd/pull/1579 was merged and fixed this
