### ISSUE TITLE
Ability to specify the 'system' object.

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#156]
Currently, there is a single system object per class, but the only way of explicitly adding methods to it is to  register them as methods on `_cheri_system_object`.  Ideally, we'd have a mechanism for specifying the system class to associate with a class, so that two libcheri consumers in the same process can provide callbacks without any possibility of code in one compartment calling callbacks intended for the other.
#24 is a related proposal.

**Comment by davidchisnall** [comment]
We probably don't need this for the paper.

**Comment by jrtc27** [comment]
libcheri was removed in #1056
