### ISSUE TITLE
Shift overflow in swp_pager_meta_cheri_get_tags

### ISSUE THREAD

**Issue by shauryapatel1995** [CTSRD-CHERI/cheribsd#1567]
Hi, the code to restore cheri tags for a page that has been swapped out has a shift overflow error. 
Consider a struct 
```
struct node {
    int arr[1020];
    struct node *next;
}
```

The function will go into an infinite loop because of an overflow error. It will cause the code to do m >>= 64 in this loop. The particular function is [here](https://github.com/CTSRD-CHERI/cheribsd/blob/main/sys/vm/swap_pager.c#L2225)

```
for (t = sb->swb_tags[i]; t != 0; t >>= j) {
		j = ffsl((long)t);
               // j will be 64 for the struct.
               // t>>= j will overflow.
	       cheri_restore_tag(p + j - 1);
		p += j;
}
```

I currently have a temporary if condition in my local to check if j is 64 and set t to 0 in that case, but would be happy to settle on an approach to fix this and contribute.

**Comment by jrtc27** [comment]
Duplicates https://github.com/CTSRD-CHERI/cheribsd/issues/1510 which is fixed in dev
