### ISSUE TITLE
getcontextx(3) on MIPS does not include CHERI CP2 state

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#163]
Currently, `getcontextx(3)` provides memory for the basic `ucontext` structure, but does not include space for CP2 state (nor a suitable pointer). As a result, passing such state to `cheri_stack_unwind(3)` is unable to update CP2 state properly.

**Comment by jrtc27** [comment]
libcheri was removed in #1056 (and MIPS is on the way out)
