### ISSUE TITLE
`shmget` not implemented on MIPS

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#165]
`shmget` appears to be missing.  The AFL driver program contains this:

```
  shm_id = shmget(IPC_PRIVATE, MAP_SIZE, IPC_CREAT | IPC_EXCL | 0600);

  if (shm_id < 0) PFATAL("shmget() failed");
```

`shm_id` is < 0 and so the `PFATAL` function prints this:

```
[-]  SYSTEM ERROR : shmget() failed
    Stop location : setup_shm(), afl-fuzz.c:1347
       OS message : Function not implemented
```

`afl-fuzz.c` is compiled as plain MIPS code, which will fork and exec a CheriABI program.  If this looks difficult and `shm_open` works then it probably wouldn't be too difficult to modify the code to use that instead (actually, it would simplify the code because creating an anonymous POSIX shared memory object and not closing it on fork is easier than passing a SysV shm object ID around via environment variables).

**Comment by RichardsonAlex** [comment]
Should be fixed by https://github.com/CTSRD-CHERI/cheribsd/commit/f8d770d68dc28a767c612a11af48110ea606cca9
