### ISSUE TITLE
Crash in `getcwd`

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#166]
I have a trivial test case that crashes with CHERIABI:

``` C
#include <unistd.h>

int main(int argc, char *argv[])
{
  char buf[10];
  getcwd(buf, 10);
  return 0;
}
```

**Comment by rwatson** [comment]
This appears to be resolved in recent CheriBSD versions, so closing under the assumption that it was fixed in CheriABI at some point in the last few months. If the problem recurs, please re-open the issue.
