### ISSUE TITLE
`setjmp` crashes in CheriABI programs

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#167]
Calling `setjmp` appears to crash in CheriABI binaries.  There doesn't appear to be a CheriABI version of setjmp in the CHERIBSD libc.

**Comment by davidchisnall** [comment]
This appears to only crash in *dynamically linked* programs, so may be an issue with tagging the `setjmp` function as a function...

**Comment by brooksdavis** [comment]
It sounds like this is CTSRD-CHERI/llvm#182

**Comment by arichardson** [comment]
Should be fixed by the lld integrated capsizefix.
