### ISSUE TITLE
KTrace CCall/CReturn support

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#17]
It would be very useful if the kernel's ktrace(1) facility could be used to track CHERI object-capability invocation/return. This would require dropping out of the CCall/CReturn fast paths to insert log entries describing the transition -- e.g., object code and data pointers, method number, and perhaps other argument information. This might be done via a software-defined exception -- but it will be a bit tricky to unwind "this is a slow path" from "this is an exception, do signal delivery".

**Comment by rwatson** [comment]
It would also be nice to have a DTrace probe -- that's an incremental change once KTrace support is there (or vice versa).

**Comment by brooksdavis** [comment]
Added CCall/CReturn tracing in af0821ececbc4102ee383b9cc9122c33eb91410a and capability exception tracing in 3a025e837cf8f397035cb19f00ad963849a08e6d.  Created #25 to track DTrace support.
