### ISSUE TITLE
Can not run clang on cheribsd-riscv64-purecap

### ISSUE THREAD

**Issue by zintown** [CTSRD-CHERI/cheribsd#1700]
I have installed llvm-riscv64-hybrid-for-purecap-rootfs by cheribuild.py, but when I run clang on cheribsd-riscv64-purecap, it failed.
the command is:
```
/opt/riscv64-hybrid/llvm-project/bin/clang-14
```
the error message is:
```
Warning: Attempted to load position-dependent executable with non-representable base: /opt/riscv64-hybrid/llvm-project/bin/clang-14
Abort trap
```
Where is the problem? 
Do I need to add specific compilation options when compiling cheribsd-riscv64-purecap？

**Comment by jrtc27** [comment]
@qwattash You added this code in https://github.com/CTSRD-CHERI/cheribsd/pull/913, but it's not ok to enforce this for non-CHERI binaries

**Comment by qwattash** [comment]
Closing this as resolved.
