### ISSUE TITLE
Complete migration of cheritest from explicit cinvoke to compiler-provided stubs

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#18]
Currently, cheritest continues to use libcheri's cinvoke functions explicitly. This is unlikely to be a much used path in the future -- and perhaps should be removed -- so we should update the test suite to use compiler-provided stubs instead.

**Comment by brooksdavis** [comment]
I'll take care of removing most uses of the invoke() entry point.  To fully remove we'll need to get rid of or significantly restructure user functions.

**Comment by brooksdavis** [comment]
Done in 71832c1.
