### ISSUE TITLE
Conditionally included tests in cheritest

### ISSUE THREAD

**Issue by michael-roe** [CTSRD-CHERI/cheribsd#181]
In cheribsd/bin/cheritest/cheritest.c, some tests are conditionally compiled in with #ifdef __CHERI_PURE_CAPABILITY.

Unfortunately, cheritest is run both on the target (to run the test) and on the host (to find out which tests are expected to be in the test output), and if these two don't agree then the Jenkins job will report a test failure.

Something needs to be fixed here.
a) (svn repo)/cheribsd/trunk/simboot/test_boot.py could be a bit smarter about handling cases when it encounters a test it didn't expect.
b) We could add a command line argument to cheritest, that asks it to leave out the pure capability tests from the list of tests.

**Comment by brooksdavis** [comment]
`test_boot.py` should be altered to not need to know what tests will be run and just care that the number is >0.

**Comment by jrtc27** [comment]
The ability to use cheritest in this way was removed in a24dc8fa08fdb5c674164097c8ea11262e49e0f8
