### ISSUE TITLE
CheriABI git hanging with quarantining enabled

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#1883]
When I try to clone a large repository onto a 2023.09.30 demo branch snapshot, and enable quarantining via `sysctl security.cheri.runtime_quaranting_default=1`, git often hangs during delta resolution:

```
robert@cheri-blossom:~% git clone https://github.com/CTSRD-CHERI/october2023-demo.git ~/october2023-demo`
Cloning into ‘/home/robert/october2023-demo’...
...
Resolving deltas:  54% (39/71)
```

The number 54% seems to vary a little but not much; I’ve also seen 55%.

`procstat` shows three git processes:
```
 1488  1298  1488  1298   1 robert   piperd     FreeBSD ELF64C git
 1489  1298  1488  1298   1 robert   -          FreeBSD ELF64C git
 1491  1298  1488  1298   1 robert   uwait      FreeBSD ELF64C git
```

On face value, it seems like the process in `uwait` is the culprit.

Sometimes I get a crash instead, documented in #1882.

Disabling quarantining allows git to run to completion without problems.

**Comment by bsdjhb** [comment]
I suspect this was fixed by #1886.
