### ISSUE TITLE
shmctl(..., IPC_RMID, NULL) broken.

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/cheribsd#189]
Calling shmctl(..., IPC_RMID, NULL) results in error (EFAULT, iirc).  I think that's because the kernel tries to copyin the third argument.

**Comment by RichardsonAlex** [comment]
I also ran into this issue and added some debug output that shows that shmctl returns an invalid ID which means that the RMID fails. I think the value was exactly 64k off the correct return value.

**Comment by brooksdavis** [comment]
I'm seeing higher than expected values on mips, but they at least work with IPC_RMID

**Comment by brooksdavis** [comment]
ipcrm now works

**Comment by brooksdavis** [comment]
It's worth noting that IPC IDs in FreeBSD are bizarre and have a 16-bit ID space and 15-bit sequence space leading to weirdly high numbers.
