### ISSUE TITLE
Stack-allocation bounds-check tests in capability ABI / sandbox mode

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#19]
Currently, cheritest checks that stack allocations have suitable bounds outside of a compartment. It should also run these tests within a compartment.

**Comment by rwatson** [comment]
NB: Commits f88259127df9bc9d6fd4d3490df0ba0c8bd2bcbc and 19ac9a6671473fc067de0fce1ba17f04d890550f that perform various stack allocations outside of a sandbox.

**Comment by jrtc27** [comment]
libcheri was removed in #1056
