### ISSUE TITLE
cheritest and cheriabitest should include threading-related tests

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#205]
Currently, we don't check that various CHERI features work in the presence of multithreading. It would be useful to start testing threading more thoroughly. However, as threading affects a number of aspects of the run-time environment and we would not want to fail to test the non-threaded case. We're a bit on the wrong side of combinatorics, but it would be tempted to add "-threaded" compilations of the test suites, as well as specific tests for threading-related behaviours. (This is further complicated by a presumed future desire to have -dynamic versions as well..)

**Comment by RichardsonAlex** [comment]
I should still have some simple pthread test programs somewhere from the initial pthreads bringup. I've been meaning to add them to cheritest but kept forgetting.

**Comment by arichardson** [comment]
This was added a while back.
