### ISSUE TITLE
c18n: Data corruption when trampolines are interrupted

### ISSUE THREAD

**Issue by dpgao** [CTSRD-CHERI/cheribsd#2077]
When a trampoline is interrupted in the middle of constructing a new trusted frame, a half-constructed invalid frame would be left on the trusted stack, which may confuse unwinders.

There are other places in the trampoline where the code assumes that it cannot be interrupted. For example, in the benchmark ABI, the stack pointer is briefly set to zero before calling the stack resolver.

**Comment by rwatson** [comment]
Work-in-progress at: https://github.com/CTSRD-CHERI/cheribsd/pull/2079

**Comment by brooksdavis** [comment]
Resolved in #2090

**Comment by dpgao** [comment]
Fixed in #2090.
