### ISSUE TITLE
Rename CheriBSD's cheritest to cheribsdtest

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#21]
The name "cheritest" is redundant to the CHERI processor's own test suite, which frequently leads to confusion. Renaming cheritest to cheribsdtest would avoid that confusion.

**Comment by rwatson** [comment]
This change should wait until swap-related tests have been merged with cheritest to avoid conflicts for Munraj.

**Comment by jrtc27** [comment]
Renamed ages ago in #736 (though quite what the right name really is continues to be unclear)
