### ISSUE TITLE
Invalid permissions for mapped object in pkg64cb with globally enabled c18n

### ISSUE THREAD

**Issue by kwitaszczyk** [CTSRD-CHERI/cheribsd#2130]
On dev (https://github.com/CTSRD-CHERI/cheribsd/commit/bdeff30fb6b1744816f43ed8a3c2f0a133d872c1) running GENERIC-MORELLO-PURECAP, `pkg64cb` crashes when executed for the first time with `security.cheri.lib_based_c18n_default` set to `1`:
```
root@cheribsd:~ # sysctl security.cheri.lib_based_c18n_default=1
security.cheri.lib_based_c18n_default: 0 -> 1
root@cheribsd:~ # gdb pkg64cb
(...)
Reading symbols from pkg64cb...
Reading symbols from /usr/lib/debug//usr/sbin/pkg64cb.debug...
(gdb) r
Starting program: /usr/sbin/pkg64cb 
The package management tool is not yet installed on your system.
Do you want to fetch and install it now? [y/N]: y
Bootstrapping pkg from http://pkg.CheriBSD.org/CheriBSD:20240617:aarch64cb, please wait...
Program received signal SIGSEGV, Segmentation fault.
Invalid permissions for mapped object.
0x0000fffffff7fe20 in ?? ()
(gdb) bt
#0  0x0000fffffff7fe20 in ?? ()
#1  0x0000fffffff7fe20 in ?? ()
Backtrace stopped: frame did not save the PC
(gdb) 
```
The crash doesn't occur if I change `security.cheri.lib_based_c18n_default` to `0`, run `pkg64cb`, change `security.cheri.lib_based_c18n_default` to `1` and run `pkg64cb` again. There must be some code path in the pkg bootstrapping process that triggers this crash.

**Comment by dpgao** [comment]
#2134 seems to fix the crash. But more thorough testing is needed.

**Comment by brooksdavis** [comment]
@kwitaszczyk I think this is now fixed and can be closed?

**Comment by kwitaszczyk** [comment]
> @kwitaszczyk I think this is now fixed and can be closed?

That's correct. Thanks!
