### ISSUE TITLE
CheriBSD `max_align_t` is wrong

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#227]
The alignment of `max_align_t` on CheriBSD is less than the alignment of `void*` for CheriABI (and less than the alignment of `void * __capability` in hybrid ABI.  This breaks anything that uses `max_align_t`.

**Comment by brooksdavis** [comment]
I think @kgudka or @arichardson have looked at this and fixed it with libc++?  I'm not entirely sure what the status is.

**Comment by arichardson** [comment]
Should be fixed by @kgudka in https://github.com/CTSRD-CHERI/clang/commit/2b009639e63b8904758b5acf42d560e6ebc6df0c
