### ISSUE TITLE
Possible problem with open(2) permission argument using csh(1) file redirection

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#230]
I'm running with a recent CheriBSD (a9d1751edc31fa03db03a124dc5f6ae2d5a4c16c) + compiler suite (LLVM: e025063dfb3d91ca0e69bd6f6f0ab22265caa2bf, Clang: a096992b7f6b044ba0dea832bfbc39df9f645020) and am seeing root-shell file redirection create files without suitable permissions:
```
root@qemu-cheri:~ # echo $shell
/bin/csh
root@qemu-cheri:~ # umask
22
root@qemu-cheri:~ # echo > foo
root@qemu-cheri:~ # ls -l foo
----------  1 root  wheel  1 Jan  1 00:06 foo
```

I'm guessing this is related to ```umask(2)``` or ```open(2)```, but a quick test with ```truncate(1)``` suggests not all is broke:
```
root@qemu-cheri:~ # ktrace truncate -s 0 test
root@qemu-cheri:~ # ls -l test
-rw-r--r--  1 root  wheel  0 Jan  1 00:06 test
```

```ktrace(1)``` shows:
```
  1042 truncate CALL  sysarch(0x1,0)
  1042 truncate RET   sysarch 0
  1042 truncate CALL  openat(AT_FDCWD,0,0x201<O_WRONLY|O_CREAT>,0644<S_IRUSR|S_IWUSR|S_IRGRP|S_IROTH>)
  1042 truncate NAMI  "test"
  1042 truncate RET   openat 3
  1042 truncate CALL  ftruncate(0x3,0)
  1042 truncate RET   ftruncate 0
  1042 truncate CALL  close(0x3)
  1042 truncate RET   close 0
  1042 truncate CALL  exit(0)
```

And the additional permission argument there appear fine. Both binaries appear to be statically linked CHERI-256:
```
root@qemu-cheri:~ # file `which truncate` `which csh`
/usr/bin/truncate: ELF 64-bit MSB executable, MIPS, MIPS-IV with CHERI-256 (CheriABI) version 1 (FreeBSD), statically linked, for FreeBSD 12.0 (1200032), FreeBSD-style, not stripped
/bin/csh:          ELF 64-bit MSB executable, MIPS, MIPS-IV with CHERI-256 (CheriABI) version 1 (FreeBSD), statically linked, for FreeBSD 12.0 (1200032), FreeBSD-style, not stripped
```

Perhaps there is a difference in how ```csh(1)``` creates files for redirection? Unclear. Regardless, a bug.

**Comment by RichardsonAlex** [comment]
This sounds like there might still be issues with the variadic calling convention in LLVM? Maybe it depends on the number of arguments before `...`. So `openat()` works but `open()` doesn't?
