### ISSUE TITLE
Moving the address field in a capability causes dereference of 0

### ISSUE THREAD

**Issue by jonwoodruff** [CTSRD-CHERI/cheribsd#246]
When we move the address field of the capability, the first user-space process, /sbin/init (standard MIPS, not cheriabi), does this and then continues to get faults endlessly:

BAD_PAGE_FAULT: pid 1 tid 100001 (init), uid 0: pc 0x12001b23c got a write fault (type 0x3) at 0
Trapframe Register Dump:
$0: 0                  at: 0                  v0: 0                  v1: 0xffffffffffffffff
a0: 0                  a1: 0x200000           a2: 0x3                a3: 0x1               
a4: 0xffffffffffffffff a5: 0                  a6: 0                  a7: 0x10              
t0: 0x16               t1: 0                  t2: 0                  t3: 0x12015b100       
s0: 0                  s1: 0                  s2: 0                  s3: 0x120160000       
s4: 0x1                s5: 0                  s6: 0                  s7: 0                 
t8: 0                  t9: 0x120083090        k0: 0                  k1: 0                 
gp: 0x12015b100        sp: 0x7fffffec80       s8: 0x7fffffec80       ra: 0x12001b238       
status: 0x4000bcf3 mullo: 0x3028201810080000; mulhi: 0x8101820283030; badvaddr: 0
cause: 0x10c; pc: 0x12001b23c
$c00: v:1 s:0 p:0007817d b:0000000000000000 l:0000008000000000 o:0 t:ffffffffffffffff
$c01: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c02: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c03: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c04: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c05: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c06: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c07: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c08: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c09: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c10: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c11: v:1 s:0 p:0007817d b:0000000000000000 l:0000008000000000 o:0 t:ffffffffffffffff
$c12: v:1 s:0 p:00068117 b:0000000000000000 l:0000008000000000 o:120005a50 t:ffffffffffffffff
$c13: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c14: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c15: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c16: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c17: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c18: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c19: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c20: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c21: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c22: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c23: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c24: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:ffffffffffffffff
$c26: v:1 s:0 p:0007817d b:0000000000000000 l:0000008000000000 o:0 t:ffffffffffffffff
$c31: v:1 s:0 p:00068117 b:0000000000000000 l:0000008000000000 o:12001b23c t:ffffffffffffffff

====================

I traced through this a bit and did not quite make it back to the source of the problem, but somewhere I would imagine that an address to a capability is referenced as an address of a pointer.  I would imagine that this is happening in the kernel as this is a standard MIPS binary.  If I understand the endianness correctly, I think this kind of logic would actually need to load from (address of capability + sizeof(capability) - 8) in order to get the 64-bit virtual address this way.

-Jon

**Comment by bsdjhb** [comment]
I suspect this is OBE.
