### ISSUE TITLE
Unaligned load/store emulation is broken

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/cheribsd#259]
Dynamically linked /usr/bin/pw is crashing on QEMU when built without unaligned accesses but not if we build qemu with unaligned access enabled (`-DCHERI_UNALIGNED`).

This may be because we changed some encodings with branch delay slots and the unaligned access emulation doesn't know about it?

**Comment by brooksdavis** [comment]
Seems to work now
