### ISSUE TITLE
Use of cheri_clear_low_ptr_bits breaks non-MIPS build

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/cheribsd#263]
Building on amd64 fails due to missing cheri includes due to the include of cheri/cheric.h to get cheri_clear_low_ptr_bits().  These should probably be moved to a non-cheri header file.

**Comment by brooksdavis** [comment]
Do we still need these with address mode?

**Comment by jrtc27** [comment]
Aren't they mainly about provenance for binary operators? With the recently-added compiler analysis maybe they can go away.

**Comment by arichardson** [comment]
Now that we infer the provenance source and more importantly no longer include the tag bit in comparisons they are no longer needed. 

We can revisit this if we ever want to make exact equals the default.

**Comment by brooksdavis** [comment]
Reopening to track removal of these macros.

**Comment by brooksdavis** [comment]
We've long since fixed the macros.
