### ISSUE TITLE
Unknown instructions in userspace branch delay slot cause kernel panic

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/cheribsd#287]
While writing some userspace assembly code I accidentally forgot to place a nop (I had a `teq $zero, $zero there) in the $cjr delay slot.
This caused the kernel to panic instead of my userspace program being killed.

```
KDB: enter: BAD OPCODE in MipsEmulateBranch
```

We should probably print an error message and abort the user program instead of killing the whole system.

**Comment by brooksdavis** [comment]
It seems a certain @arichardson person added this drop to DDB in 6565e4c8f853e111bfde70497cac83f1ad1b4c56. 😄 We might just want to revert that change.

**Comment by arichardson** [comment]
Three months is a long time... But I think we still don't handle CJR/CJALR in this code.

**Comment by bsdjhb** [comment]
OBE as MIPS is now gone.
