### ISSUE TITLE
Signal delivery is broken in cheriabi

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#29]
sigaction takes a struct that contains a code capability.  Cheriabi doesn't appear to add a `cheri_` compat version to extract the code capability.  We probably also need some changes to the signal delivery code to install a code capability, as well as a code pointer, though I believe that we have some of this currently to allow signals to run outside of a sandbox when raised in the sandbox.

**Comment by brooksdavis** [comment]
When I did the first pass of CheriABI function pointers were were integers.  I'll take care of this when I did the reaudit of syscalls on for (u)intptr_t.

**Comment by davidchisnall** [comment]
Note that this is a blocker for the C tests that I'm currently working on, so any progress that can be made would help.

**Comment by brooksdavis** [comment]
As of cb15cfdc9 sigaction installs and runs handlers, but doesn't call sa_action ones correctly or set `$c12` properly.

**Comment by davidchisnall** [comment]
The `sa_action` part is the most important, as I need to be able to poke the register file to skip the faulting instruction in the tests.  If `$c12` is not set correctly, does this mean that `$t9` is?  If so, I can work around that with a little asm trampoline that sets up `$c12` by setting it to `$pcc` with the offset set to `$t9` and then jumps to the C handler.

**Comment by brooksdavis** [comment]
It looks like `$t9` matches `$c12` so fixing the signal code property is required.
