### ISSUE TITLE
process_mux_new_session: tcgetattr: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/cheribsd#302]
When running the libc++ testsuite I get lots of `process_mux_new_session: tcgetattr: Inappropriate ioctl for device` warning messages printed to the log. This is probably related to using `ssh -tt` to run the test programs.

**Comment by arichardson** [comment]
I was not seeing these before today so it might be related to the latest merge?

**Comment by brooksdavis** [comment]
Any idea if this is still happening?

**Comment by arichardson** [comment]
Haven't seen this lately. Will reopen if it's still reproduceable
