### ISSUE TITLE
printf %p prints 32-bit value

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#34]
Printing a capability with base `0x7fffffe274` and offset 0 prints `0xffff03fe` with `%p`.

**Comment by brooksdavis** [comment]
Hmm, printing a completely different pointer also produced `0xffff03fe`.

**Comment by brooksdavis** [comment]
It's not immediately clear to me why `(uintmax_t)(uintptr_t)GETARG(void *)` is producing a constant `0xffff03fe` rather than the base plus the offset.

**Comment by brooksdavis** [comment]
Since %p is implementation defined in the standard I'm somewhat tempted to make it produce something more interesting than the virtual address of the pointer, but that might be too surprising.

**Comment by davidchisnall** [comment]
The `void*` -> `uintptr_t` cast will not change the representation, only the interpretation.  I'm not sure what `uintmax_t` is defined to in cheriabi.  If it's a primitive integer type, then this will get the offset of the value.  If it's `__uintptr_t` then it will not change the representation and the next implicit cast to a primitive type will get the offset.
