### ISSUE TITLE
Fix KDB when dtrace is compiled into the kernel

### ISSUE THREAD

**Issue by nicomazz** [CTSRD-CHERI/cheribsd#397]
The issue will be fixed by [this](https://reviews.freebsd.org/D24018). We should merge it here as well.

**Comment by nicomazz** [comment]
Actually, that patch solves the problem only for RISC-V. A similar change is needed for the other platforms.

**Comment by nicomazz** [comment]
The issue is now fixed for MIPS, but likely not for the other platforms.

**Comment by brooksdavis** [comment]
It looks like we need to merge from upstream to pick up the riscv fix, but that will happen eventually and we've fixed mips locally.
