### ISSUE TITLE
Possible user/group lookup / NSS problems in CheriABI?

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#40]
When rm(1) tries to confirm deletion on an immutable (schg) file, the prompt does not correctly display user and group names:

root@beri1:/tmp # ./rm foo
override rw-r--r--  0/0 schg for foo? y
rm: foo: No error: 0

This could be an issue with NSS?

(Note that error output problem above is described in #37, a separate issue.)

**Comment by brooksdavis** [comment]
This appears to be fixed.  I suspect CTSRD-CHERI/llvm@dfe2b5ac0bae016e1886768ee8cfa1130b76ce1f fixed this since it appeared to effect all the NSS related files.

```
root@beri1:/home/ctsrd # chflags schg schg-file
root@beri1:/home/ctsrd # rm schg-file 
override rw-r--r--  root/ctsrd schg for schg-file? y
rm: schg-file: Operation not permitted
```
