### ISSUE TITLE
Unexpected cheriabitest failures

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/cheribsd#406]
Running 365e480c373c9b3d72b92dda8e1bf7848a83e6e9, `cheriabitest` reports:

```
Unexpected failures:
  test_initregs_stack: stack offset 3fdcf50 (expected range 7fc000 to 7fc000)
  test_bounds_global_static_uint8_array65537: global: incorrect length (expected 65537, got 65664)
  test_bounds_global_uint8_array65537: global: incorrect length (expected 65537, got 65664)
  test_bounds_extern_global_array65537: global: incorrect length (expected 65537, got 65664)
  test_unaligned_capability_copy_memcpy: Expected child termination with signal 6
  test_unaligned_capability_copy_memmove: Expected child termination with signal 6
```

I think these result from...
* `initregs_stack` : having a larger stack than when the test was written
* `bounds_*`,  stronger Concentrate alignment requirements than when the tests were written
* `unaligned_*`, `memcpy`/`memmove` now just strips the tag and doesn't abort in these cases

If that's right (@arichardson is probably the person who knows), I'll go ahead and update the tests in the obvious ways.

**Comment by arichardson** [comment]
Yes, all caused by changing stuff without updating tests. Thanks!

**Comment by jrtc27** [comment]
I recognise all those as the usual known failures I've seen and ignored for the past ~forever :)
