### ISSUE TITLE
libcheri_type.c assumes otype field has 24 bits

### ISSUE THREAD

**Issue by dodsonmg** [CTSRD-CHERI/cheribsd#408]
https://github.com/CTSRD-CHERI/cheribsd/blob/68e2a095a015955bb9f6daff338a712247192e95/lib/libcheri/libcheri_type.c#L52-L53

Presumably this is a holdover from uncompressed capabilities and should be 18 (or conditionally set based on whether compression is in use)?

Because the type capability returned by `lib_cheri_type_alloc` stores the type in the base field, I expected this function to happily return a type capability with a type > 18 bits, but then to fail when using that type capability to seal another capability, as the type value is transferred from the base field of the type capability to the type field of the capability being sealed.

It actually fails when generating the type capability using `cheri_maketype` in cheric.h.  The type capability is derived from the root sealing capability, which has a length of 0x20000.  This, very sensibly, prevents you from deriving a type capability with more bits in the base than can be transferred to the type field of the sealed capability.

A hardcoded fix straightforward (and it works); however, I assume there's a cleaner fix that is conditioned on whether we're using 256 or 128 bit capabilities.  If you could point me to a similar conditional, I'm happy to implement.

**Comment by brooksdavis** [comment]
I'd suggest we go with a hardcoded fix that works for CHERI Concentrate 128-bit capabilities. We're in the process of depreciating 256-bit support as we don't think there's a commercial future for it as implemented.

That being said, where we should be storing this per-architecture constant is an interesting question.
