### ISSUE TITLE
Support Non-Legacy VirtIO Network Device

### ISSUE THREAD

**Issue by jrtc27** [CTSRD-CHERI/cheribsd#468]
5.1.6.1 Legacy Interface: Device Operation

> The legacy driver only presented num_buffers in the struct virtio_net_hdr when VIRTIO_NET_F_MRG_RXBUF was negotiated; without that feature the structure was 2 bytes shorter.

TinyEMU does not support VIRTIO_NET_F_MRG_RXBUF, so the feature is not negotiated and FreeBSD does not include the field in its header, resulting in all network packets being corrupted. It should learn that non-legacy (i.e. VIRTIO_F_VERSION_1) network devices always include the field, even if the feature is not negotiated, and it should be set to 1 to be strictly spec-conforming (though TinyEMU will ignore it entirely).

**Comment by jrtc27** [comment]
Fix submitted for review: https://reviews.freebsd.org/D25132 (and associated parent revision).

**Comment by brooksdavis** [comment]
We've got one fix to loop back, but I think we're done for FETT purposes.
