### ISSUE TITLE
Use .incbin to embed MFS image.

### ISSUE THREAD

**Issue by qwattash** [CTSRD-CHERI/cheribsd#477]
This avoids the need to objcopy the mfs-root image and simplify the makefile by not needing to keep a separate list of output ABI flags to specify to objcopy.
This also avoids the need to teach objcopy to change eflags [llvm PR/406](https://github.com/CTSRD-CHERI/llvm-project/pull/406).

**Comment by jrtc27** [comment]
Fixed in d8173d99b0c15b0ae1c0cfc245f7bd1f8c44f1ea
