### ISSUE TITLE
CheriABI: sucap(9) does not take a permissions argument

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#58]
Currently, the kernel's ```sucap(9)``` function accepts most capability fields, but not a permissions field. As we begin to divorce executable capabilities (r+x) and data capabilities (r+w), we will need to set permissions more specifically here. But will we always know what permissions are required?

**Comment by brooksdavis** [comment]
Adding permissions argument in 246aae553b831d7b15d14375bf2f696068217c6a.  All current uses want CHERI_CAP_USER_DATA_PERMS.
