### ISSUE TITLE
RISC-V lacks support for a userspace sealing capability

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/cheribsd#634]
mips returns a sealing capability via `sysarch()`. This was expedient, but is a poor match for (e.g.) co-processes (where types can't be shared between processes in the same address space). We probably need an allocation syscall working from a resource that is per address space. At a minimum, processes would hold the allocated types until they exit (and likely until they are revoked unless we can prevent sealing caps from being shared between processes.)

See some discussion in #632

**Comment by jrtc27** [comment]
Fixed by #723 ages ago
