### ISSUE TITLE
Teach kernel setjmp/longjmp about CHERI

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#68]
Kernel `setjmp`/`longjmp` are used in DDB and GDB in order to support debugger reentrance; they should also preserve capability registers. More generally, they should be reviewed for 64-bit safety.

**Comment by jrtc27** [comment]
For posterity, this bug does in fact still exist in the hybrid CHERI-MIPS kernel: https://github.com/CTSRD-CHERI/cheribsd/blob/35e3ade49ea876fca3f85780236e26fdd1a1f133/sys/mips/mips/support.S#L1194-L1196

Other CHERI kernels, whether hybrid or pure-capability, are unaffected, including the (incomplete as it was never fully merged) pure-capability CHERI-MIPS kernel, which has a separate implementation.
