### ISSUE TITLE
Teach CheriABI mmap(2) about 128-bit alignment rules -- and also figure out how to deal with imprecision

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#69]
Today, CheriABI `mmap(2)` is unaware of the effects of imprecision for 128-bit capabilities. We need to:

(a) teach `mmap(2)` that, for suitably sized allocations or mappings, stronger alignment may be required;

(b) for sizes that cannot be aligned with full precision, the ability to cause `mmap(2)` to fail (perhaps as a default?); and

(c) if that failure is not desirable, then possibly add a reservation scheme so that imprecise mappings can implicitly be extended to prevent accidental further mappings within the larger imprecise region -- semantics to be determined (if any).

There are undoubtably further implications.

**Comment by brooksdavis** [comment]
Other than providing a way to not fail on under sized allocations, this has been done for a while
