### ISSUE TITLE
Check permissions in vm_fault_quick_hold_pages

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/cheribsd#735]

**Comment by jrtc27** [comment]
Or if they're capabilities just and the permissions for the pages?

**Comment by brooksdavis** [comment]
I think we don't want to do that because we'd potentially create a panic vector.

**Comment by jrtc27** [comment]
Yeah, I came to that conclusion myself. I think we probably want to do _both_ for safety, i.e. have the checks be what should catch everything, and the permissions in case any API consumer tries to do more than it should (or the checks have a bug and are insufficient)? Same goes for bounds.

**Comment by jrtc27** [comment]
Although one could restrict the safety net to just being for a pure-capability kernel, and treat it as now a kernel memory safety problem once you have the kernel mappings, given it'll likely be painful to make those all capabilities in a hybrid kernel.

**Comment by brooksdavis** [comment]
I agree that doing both might be sensible in purecap.

@bsdjhb also pointed out that the page pointers created are physical addresses so we probably need physical address capabilities to restrict them properly.

**Comment by jrtc27** [comment]
Hm it's worse than that, you get pointers to the `vm_page_t`'s. I naively assumed this was doing the lookup and pmap all at once...

**Comment by bsdjhb** [comment]
In almost all cases, the reason callers use this function is to avoid mapping the pages into the kernel's address space at all.  Generally you are just going to pass the pages down to a driver that will map them for DMA, so it just pulls the physical address directly out of the `vm_page_t` via `VM_PAGE_TO_PHYS`.  For the few places that need a mapping, they are using the architecture-specific direct mapping of RAM and access one page at a time, or they use the sf_buf(9) API to temporarily map pages (which uses the direct mapping when it exists)
