### ISSUE TITLE
statically linked userspace binaries

### ISSUE THREAD

**Issue by gvnn3** [CTSRD-CHERI/cheribsd#748]
- [x] outstanding hybrid cheritest failures (bounds, vm, string)
- [x] outstanding purecap cheriabitest failures:
  - [x] bounds
  - [x] vm
  - [x] open
  - [x] setjmp/longjmp

**Comment by arichardson** [comment]
Hopefully the first one will be fixed by the new model. However, it might also be the morello compiler not adding sufficient padding, in which case we can ignore it for now. Will check what the compiler does tomorrow morning.

**Comment by bsdjhb** [comment]
Was the vm one the PTE one?  If so, it is now fixed.

**Comment by jrtc27** [comment]
I believe so.
