### ISSUE TITLE
Mismatched brackets in cheric.h.

### ISSUE THREAD

**Issue by jacobbramley** [CTSRD-CHERI/cheribsd#786]
I noticed `cheri_codeptr` trying to use it. Vim's syntax highlighting found `cheri_setbounds_changetype`.

https://github.com/CTSRD-CHERI/cheribsd/blob/ecbc5cc44c5e845074836fe92c2eb8fc100862d2/sys/cheri/cheric.h#L79
https://github.com/CTSRD-CHERI/cheribsd/blob/ecbc5cc44c5e845074836fe92c2eb8fc100862d2/sys/cheri/cheric.h#L122

**Comment by arichardson** [comment]
We probably want to update cheric.h to use the newer cheriintrin.h macros, but those should definitely be fixed.

**Comment by jrtc27** [comment]
The first one (and its friend below) should Justin be removed now we have the polymorphic builtins, though not sure we used those weird versions even before.

**Comment by jrtc27** [comment]
Fixed in #797
