### ISSUE TITLE
Multi-stack support for libcheri compartments

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#9]
Currently, libcheri compartments are single-threaded and non-reentrant. Support should be added so that compartments can stash a set of stacks, rather than one stack, and pick the first available one. If the set is exhausted, we may need to allocate more -- or perform some garbage collection activity. It's not yet clear how we should handle compartment faults: a cleanly returning compartment can return its own stack. But a faulting compartment doesn't have the opportunity to do so. Possibly the libcheri runtime should forceably return the stack in that case as part of unwinding?

Depends on #8.

**Comment by jrtc27** [comment]
libcheri was removed in #1056
