### ISSUE TITLE
Make ambient capabilities non-global by default

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/cheribsd#95]
Local capabilities are constrained in flow between compartments, whereas global capabilities are permitted to flow between compartments. This works well to prevent undesired leakage of compartment stack references, etc, requiring that global (heap) memory be explicitly allocated for delegation between security domains. However, capabilities used with ambient authority (i.e., in the default within a process) are global, so as sandboxes are allocated, thread pointers, etc, can be accidentally or unsafely delegated to compartments. This change proposal is to remove `CHERI_PERM_GLOBAL` from the default code and data capabilities delegated to the user address space, and to add a new `cheri_makeglobal(2)` interface (via `sysarch(2)`?) that allows a local capability to be upgraded (re-cast) as global so that it can be delegated to a compartment. This will require that ambient software take explicit action to make a capability delegable to a compartment, limiting the opportunity for accidental leaks.

**Comment by jrtc27** [comment]
libcheri was removed in #1056
