### ISSUE TITLE
Merge packaged base branch?

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/cheribsd#97]
It would be nice if we could build a package set from base so that people doing software work can do binary upgrades.

**Comment by brooksdavis** [comment]
Is the base packaging work going on in a separate branch?  I'd presumably need to get us merged up to HEAD at a minimum even if it's in another branch. I think we may be in a good place to do that once I'm back next week.  (I'll need to hold a lock on the official head for a few days.)

**Comment by davidchisnall** [comment]
Yes, in the release-pkg branch.  I'm not sure how easy it is to cherry-pick the relevant commits.  We could possibly encourage the people working on it to push it to head in an incomplete state...

**Comment by brooksdavis** [comment]
The basics of this are in via head.  Actually making packaging work for cheribsd would be an additional bit of work since we'd have to add appropriate annotations for package metadata.  We should look into this, but I'm closing this issue for now.
